### ISSUE TITLE
[BUG] MQTT broker service - Address already in use (Bind failed)

### ISSUE THREAD

**Issue by shiipou** [alteroo/headwind-mdm-docker#2]
Hi, I've build your image accessible to `nocturlab/h-mdm:latest`
But i can't launch it on my cluster.

Here what I've done : 
I've create a script named `./h-mdm.sh` that contain the following : 
```bash
#!/bin/sh

image='nocturlab/h-mdm:latest'
name='h-mdm'
network='ingress_net'
extra_opts='--tty --replicas 1 --update-delay 20s --update-parallelism 1'
volumes=""
env_vars='-e HMDM_SQL_HOST=db_postgres -e HMDM_SQL_PORT=5432 -e HMDM_SQL_BASE=hmdm -e HMDM_SQL_USER=hmdm -e HMDM_SQL_PASS=mypassword -e HMDM_LANGUAGE=fr -e HMDM_TOMCAT_PORTOCOL=http'
ports=''

docker service ps "$name" >> /dev/null
if [ "$?" -eq "0" ]; then
  docker service rm "$name"
fi

docker service create \
  --name "$name" \
  --network "$network" \
  $extra_opts \
  $volumes \
  $env_vars \
  $ports \
  --label traefik.enable=true \
  --label traefik.http.routers.h-mdm_http.rule='Host(`mdm.example.com`)' \
  --label traefik.http.routers.h-mdm_http.entrypoints=http \
  --label traefik.http.routers.h-mdm_http.middlewares=https-redirect@docker \
  --label traefik.http.routers.h-mdm_https.rule='Host(`mdm.example.com`)' \
  --label traefik.http.routers.h-mdm_https.entrypoints=https \
  --label traefik.http.routers.h-mdm_https.tls.certresolver=certbot \
  --label traefik.http.services.h-mdm.loadbalancer.server.port=8080 \
  "$image"
```

And I've launched it : 
```bash
chmod +x ./h-mdm.sh && ./h-mdm.sh
```

Here the logs :

```bash
# ~/ : docker service logs -f --raw h-mdm
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Tomcat started.
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully

[ ok ] Restarting PostgreSQL 11 database server: main.
ls: cannot access '/var/lib/tomcat*': No such file or directory
ls: cannot access '/webapps': No such file or directory
PostgreSQL database setup
=========================
Make sure you've installed PostgreSQL and created the database:
# CREATE USER hmdm WITH PASSWORD 'topsecret';
# CREATE DATABASE hmdm WITH OWNER=hmdm;

postgresql://hmdm:mypassword@db_postgres:5432/hmdm

File storage setup
==================
Please choose where the files uploaded to Headwind MDM will be stored
If the directory doesn't exist, it will be created
##### FOR TOMCAT 9, USE SANDBOXED DIR: /var/lib/tomcat9/work #####

Default Headwind MDM directory [/opt/hmdm]


Web application setup
=====================
Headwind MDM requires access from Internet
Please assign a public domain name to this server


Ready to install!
Location on server: 
URL: http://0.0.0.0:8080/hmdm
Tomcat config file created: /usr/local/tomcat/conf/Catalina/localhost//hmdm.xml
Deploying hmdm-3.23.3-os.war to Tomcat: /usr/local/tomcat/webapps//hmdm.war
..............
Deployment successful, initializing the database...
cat: ./install/sql/hmdm_init..sql: No such file or directory

======================================
Headwind MDM has been installed!
To continue, open in your web browser:
http://0.0.0.0:8080/hmdm
Login: admin:admin
ERROR:  relation "userroles" does not exist
LINE 1: UPDATE userroles SET name = 'Super Administrator', descripti...
               ^
ERROR:  relation "userroles" does not exist
LINE 1: UPDATE userroles SET name = 'Administrator', description = '...
               ^
ERROR:  relation "userroles" does not exist
LINE 1: UPDATE userroles SET name = 'User', description = 'User for ...
               ^
ERROR:  relation "userroles" does not exist
LINE 1: UPDATE userroles SET name = 'Observer', description = 'The o...
               ^
ERROR:  relation "groups" does not exist
LINE 1: UPDATE groups SET name = 'Default' WHERE id = '1';
               ^
ERROR:  relation "configurations" does not exist
LINE 1: UPDATE configurations SET name = 'Default', description = 'B...
               ^
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
18-Nov-2020 12:58:38.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.57
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 30 2020 21:49:10 UTC
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.57.0
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.8.0-7625-generic
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_265-b01
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
18-Nov-2020 12:58:38.281 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.24] using APR version [1.6.5].
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
18-Nov-2020 12:58:38.282 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
18-Nov-2020 12:58:38.286 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
18-Nov-2020 12:58:38.334 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-Nov-2020 12:58:38.342 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
18-Nov-2020 12:58:38.349 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 324 ms
18-Nov-2020 12:58:38.362 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-Nov-2020 12:58:38.363 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.57
18-Nov-2020 12:58:38.368 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/hmdm.xml]
18-Nov-2020 12:58:40.210 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[HMDM-LOGGING] : Using log4j configuration from: file:///log4j-hmdm.xml
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:41 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:41 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:41 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:41 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2020-11-18 12:58:42 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-11-18 12:58:42 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2020-11-18 12:58:43 [INFO] com.hmdm.persistence.ConfigurationDAO : Base URL: http://0.0.0.0:8080/hmdm
[HMDM-INITIALIZER]: Application initialization was successful
[HMDM-INITIALIZER]: Created a signal file for application initialization completion: /hmdm_install_flag
2020-11-18 12:58:43 [ERROR] com.hmdm.notification.guice.module.NotificationMqttTaskModule : Failed to create MQTT broker service
java.io.IOException: Failed to bind to server socket: mqtt://0.0.0.0:31000 due to: java.net.BindException: Address already in use (Bind failed)
	at org.apache.activemq.util.IOExceptionSupport.create(IOExceptionSupport.java:34)
	at org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:146)
	at org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
	at org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
	at org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
	at org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
	at org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
	at com.hmdm.notification.guice.module.NotificationMqttTaskModule.initBrokerService(NotificationMqttTaskModule.java:43)
	at com.hmdm.notification.guice.module.NotificationMqttTaskModule.init(NotificationMqttTaskModule.java:28)
	at com.hmdm.guice.Initializer.initTasks(Initializer.java:165)
	at com.hmdm.guice.Initializer.contextInitialized(Initializer.java:133)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1822)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.<init>(ServerSocket.java:252)
	at javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
	at org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
	... 22 more
18-Nov-2020 12:58:43.128 INFO [localhost-startStop-1] nonapi.io.github.classgraph.classloaderhandler.lifecycle.ServletLifeCycleListener.contextInitialized Servlet context initialized
2020-11-18 12:58:43 [INFO] org.reflections.Reflections : Reflections took 49 ms to scan 9 urls, producing 326 keys and 688 values 
18-Nov-2020 12:58:44.139 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/hmdm.xml] has finished in [5,770] ms
18-Nov-2020 12:58:44.141 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Nov-2020 12:58:44.146 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 5796 ms
```

What I've got : 

![image](https://user-images.githubusercontent.com/38187238/99534526-d5e89980-29a7-11eb-9d86-63286ba31ede.png)

Please can you help me to make it work ? 
Thank you.

**Comment by shiipou** [comment]
Ok my bad...

To access I have to go to mdm.example.com/**hmdm/**
